# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VersiWorld Project
email: jefjohms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Physics project for Quinn Mosher and Jeffrey M Johnson Year 2 game programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gravballs.github.io/VersiWorld/" # the base hostname & protocol for your site
twitter_username: 
github_username:  GravBalls

# Build settings
markdown: kramdown
